<?php


namespace app\web\controller;


use think\Request;
use app\web\model\Config as ConfigModel;

/**
 * 条码配置管理
 */
class Config extends Controller
{
    protected $configModel;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->configModel = new ConfigModel();
    }

    /**
     * 函数功能描述 查询当前配置信息
     * Date: 2021/1/5
     * Time: 9:40
     * @author gxd
     */
    public function getBarcodeConfig() {
        $config_info = $this->configModel->getList(["config_group"=>"barcode","com_id"=>$this->com_id], "config_name,config_value");
        return $this->renderSuccess($config_info,"查询成功");
    }

    /**
     * 函数功能描述 条码配置
     * Date: 2021/1/4
     * Time: 17:24
     * @author gxd
     */
    public function barcodeConfig(Request $request) {
        $data = $request->post();
        $where_base["config_group"] = "barcode";
        $where_base["com_id"] = $this->com_id;
        $data_base = ["config_group"=>"barcode","com_id"=>$this->com_id];
        $where_auto_generate = array_merge($where_base,["config_name"=>"auto_generate"]);
        if(isset($data["auto_generate"])) {
            $config_info = $this->configModel->getOne($where_auto_generate);
            if ($config_info) {
                $config_info->config_value=1;
                $config_info->save();
            } else {
                $data = $data_base;
                $data["config_name"] = "auto_generate";
                $data["config_value"] = 1;
                $this->configModel->save($data);
            }
        } else {
            $config_info = $this->configModel->getOne($where_auto_generate);
            if ($config_info) {
                $config_info->config_value=0;
                $config_info->save();
            } else {
                $data = $data_base;
                $data["config_name"] = "auto_generate";
                $data["config_value"] = 0;
                $this->configModel->save($data);
            }
        }
        $where_item_type = array_merge($where_base,["config_name"=>"item_type"]);
        if(isset($data["item_type"])) {
            $config_info = $this->configModel->getOne($where_item_type);
            if ($config_info) {
                $config_info->config_value=1;
                $config_info->save();
            } else {
                $data = $data_base;
                $data["config_name"] = "item_type";
                $data["config_value"] = 1;
                $this->configModel->save($data);
            }
        } else {
            $config_info = $this->configModel->getOne($where_item_type);
            if ($config_info) {
                $config_info->config_value=0;
                $config_info->save();
            } else {
                $data = $data_base;
                $data["config_name"] = "item_type";
                $data["config_value"] = 0;
                $this->configModel->save($data);
            }
        }
        $where_type = array_merge($where_base,["config_name"=>"type"]);
        $config_info = $this->configModel->getOne($where_type);
        if ($config_info) {
            $config_info->config_value=$data["type"];
            $config_info->save();
        } else {
            $data = $data_base;
            $data["config_name"] = "item_type";
            $data["config_value"] = $data["type"];
            $this->configModel->save($data);
        }
        $where_firm_code = array_merge($where_base,["config_name"=>"firm_code"]);
        $config_info = $this->configModel->getOne($where_firm_code);
        if ($config_info) {
            $config_info->config_value=$data["firm_code"];
            $config_info->save();
        } else {
            $data = $data_base;
            $data["config_name"] = "firm_code";
            $data["config_value"] = $data["firm_code"];
            $this->configModel->save($data);
        }
        $where_start_value = array_merge($where_base,["config_name"=>"start_value"]);
        $config_info = $this->configModel->getOne($where_start_value);
        if ($config_info) {
            $config_info->config_value=$data["start_value"];
            $config_info->save();
        } else {
            $data = $data_base;
            $data["config_name"] = "start_value";
            $data["config_value"] = $data["start_value"];
            $this->configModel->save($data);
        }
        return $this->renderSuccess([],"操作成功");
    }

}